git ls-remote --heads https://github.com/<GEETHA9999>/<DevOPS->.git
name: myfirstpipeline

on:
  workflow_dispatch:

jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'master'
          owner: 'GEETHA9999'
          repository: 'DevOPS-'
          git branch -M master
           git push -u origin master
           Cloning into 'DevOPS-'...
