name: myfirs pipeline

on:
  workflow_dispatch: 

jobs:
  clone-repo-job
    runs-on: ubuntu-latest
    steps:
      - name: Clone private repo via HTTPS
        uses: actions/checkout@vmain
        with:
          repository: GEETHA9999/DevOPS-
          ref: main
          path: 'external-repo'
